apiVersion: v1
kind: Config
current-context: ${CLUSTER_NAME}
contexts: [{name: ${CLUSTER_NAME}, context: {cluster: ${CLUSTER_NAME}, user: user-1}}]
users: [{name: user-1, user: {auth-provider: {name: gcp}}}]
clusters:
- name: ${CLUSTER_NAME}
  cluster:
    server: "https://${CLUSTER_API_URL}"
    certificate-authority-data: "${CA_CERTIFICATE}"